title: shreyateeza da blog
author: shreyateeza
email: shreyateeza@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm glad you are here. I plan to talk about everything I want to talk about ;P 
  I hope through this blog I can reach to people effectively 
  with love and zeal and lots of happiness. :D

# social links
twitter_username: shreyateeza
github_username:  shreyateeza

theme: architect
show_excerpts: true # set to false to remove excerpts on the homepage
